name: HTTP App workflow

on:
  push:
    branches:
      - main
      - master
      - "feature/**"

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install node packages
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Compile source code
        run: npm run build