name: HTTP App workflow
on:
  push:
    branches:
      - main 
      - master
      - "feature/**"
  # pull_request:
  #   branches:
  #     - main
jobs:
  test and build:
    runs_on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v5
      - name: setup node js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install node packages 
        run: npm install

      # - name: run test
      #   run: npm run test

      - name: compile source code
        run: npm run build
